name = "my-worker"
type = "javascript"

account_id = "4806f2425c6560e67d083f843b83dd5d"
workers_dev = true
route = ""
zone_id = ""

compatibility_date = "2025-02-26"

[build]
command = ""

[vars]
ENV = "production"
